"""
HAL 초기화 코드 생성기

스키매틱에서 추출한 핀/주변장치 정보로
MCU별 HAL 초기화 코드를 자동 생성.

지원: STM32 HAL, Arduino, ESP-IDF
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from jinja2 import Template
from loguru import logger

from .pin_analyzer import PinAnalyzer, PinFunction


# ─── Jinja2 템플릿 ────────────────────────────────────────

STM32_HAL_TEMPLATE = Template("""\
/* Auto-generated by hwdesign — STM32 HAL Init */
/* Board: {{ board_name }} | MCU: {{ mcu_value }} */

#include "main.h"

{% for periph in peripherals %}
{% if periph.type == "I2C" %}
I2C_HandleTypeDef hi2c{{ periph.instance }};

void MX_I2C{{ periph.instance }}_Init(void) {
    hi2c{{ periph.instance }}.Instance = I2C{{ periph.instance }};
    hi2c{{ periph.instance }}.Init.ClockSpeed = {{ periph.speed | default(100000) }};
    hi2c{{ periph.instance }}.Init.DutyCycle = I2C_DUTYCYCLE_2;
    hi2c{{ periph.instance }}.Init.OwnAddress1 = 0;
    hi2c{{ periph.instance }}.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
    HAL_I2C_Init(&hi2c{{ periph.instance }});
}
{% endif %}
{% if periph.type == "SPI" %}
SPI_HandleTypeDef hspi{{ periph.instance }};

void MX_SPI{{ periph.instance }}_Init(void) {
    hspi{{ periph.instance }}.Instance = SPI{{ periph.instance }};
    hspi{{ periph.instance }}.Init.Mode = SPI_MODE_MASTER;
    hspi{{ periph.instance }}.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_16;
    hspi{{ periph.instance }}.Init.Direction = SPI_DIRECTION_2LINES;
    hspi{{ periph.instance }}.Init.DataSize = SPI_DATASIZE_8BIT;
    HAL_SPI_Init(&hspi{{ periph.instance }});
}
{% endif %}
{% if periph.type == "UART" %}
UART_HandleTypeDef huart{{ periph.instance }};

void MX_USART{{ periph.instance }}_UART_Init(void) {
    huart{{ periph.instance }}.Instance = USART{{ periph.instance }};
    huart{{ periph.instance }}.Init.BaudRate = {{ periph.baudrate | default(115200) }};
    huart{{ periph.instance }}.Init.WordLength = UART_WORDLENGTH_8B;
    huart{{ periph.instance }}.Init.StopBits = UART_STOPBITS_1;
    huart{{ periph.instance }}.Init.Parity = UART_PARITY_NONE;
    huart{{ periph.instance }}.Init.Mode = UART_MODE_TX_RX;
    HAL_UART_Init(&huart{{ periph.instance }});
}
{% endif %}
{% if periph.type == "ADC" %}
ADC_HandleTypeDef hadc{{ periph.instance }};

void MX_ADC{{ periph.instance }}_Init(void) {
    hadc{{ periph.instance }}.Instance = ADC{{ periph.instance }};
    hadc{{ periph.instance }}.Init.Resolution = ADC_RESOLUTION_12B;
    hadc{{ periph.instance }}.Init.ScanConvMode = DISABLE;
    hadc{{ periph.instance }}.Init.ContinuousConvMode = DISABLE;
    HAL_ADC_Init(&hadc{{ periph.instance }});
}
{% endif %}
{% endfor %}

{% for pin in gpio_pins %}
/* GPIO: {{ pin.name }} — {{ pin.port }}{{ pin.number }} */
{% endfor %}

void MX_GPIO_Init(void) {
    GPIO_InitTypeDef GPIO_InitStruct = {0};

{% for pin in gpio_pins %}
    /* {{ pin.name }} */
    GPIO_InitStruct.Pin = GPIO_PIN_{{ pin.number }};
    GPIO_InitStruct.Mode = GPIO_MODE_{{ pin.mode | default("OUTPUT_PP") }};
    GPIO_InitStruct.Pull = GPIO_{{ pin.pull | default("NOPULL") }};
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIO{{ pin.port }}, &GPIO_InitStruct);
{% endfor %}
}

void SystemClock_Config(void) {
    /* TODO: Configure system clock based on board requirements */
}

int main(void) {
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
{% for periph in peripherals %}
{% if periph.type == "I2C" %}
    MX_I2C{{ periph.instance }}_Init();
{% elif periph.type == "SPI" %}
    MX_SPI{{ periph.instance }}_Init();
{% elif periph.type == "UART" %}
    MX_USART{{ periph.instance }}_UART_Init();
{% elif periph.type == "ADC" %}
    MX_ADC{{ periph.instance }}_Init();
{% endif %}
{% endfor %}

    while (1) {
        /* Main loop */
    }
}
""")

ARDUINO_TEMPLATE = Template("""\
// Auto-generated by hwdesign — Arduino Sketch
// Board: {{ board_name }} | MCU: {{ mcu_value }}

{% if has_i2c %}
#include <Wire.h>
{% endif %}
{% if has_spi %}
#include <SPI.h>
{% endif %}

{% for pin in gpio_pins %}
#define PIN_{{ pin.name | upper }} {{ pin.arduino_pin }}
{% endfor %}

void setup() {
    Serial.begin({{ baudrate | default(115200) }});
{% if has_i2c %}
    Wire.begin();
{% endif %}
{% if has_spi %}
    SPI.begin();
{% endif %}

{% for pin in gpio_pins %}
    pinMode(PIN_{{ pin.name | upper }}, {{ pin.mode | default("OUTPUT") }});
{% endfor %}

    Serial.println("{{ board_name }} initialized");
}

void loop() {
    /* Main loop */
    delay(100);
}
""")


@dataclass
class PeripheralInfo:
    periph_type: str  # I2C, SPI, UART, ADC, PWM
    instance: int = 1
    speed: int = 0
    baudrate: int = 115200


@dataclass
class GPIOPin:
    name: str
    port: str = "A"
    number: int = 0
    mode: str = "OUTPUT_PP"
    pull: str = "NOPULL"
    arduino_pin: int = 0


@dataclass
class HALCodeResult:
    code: str
    framework: str
    mcu_family: str
    peripherals: list[PeripheralInfo] = field(default_factory=list)
    gpio_pins: list[GPIOPin] = field(default_factory=list)
    output_path: str = ""


class HALCodeGenerator:
    """
    MCU HAL 초기화 코드 생성기

    지원 프레임워크:
    - stm32_hal: STM32 HAL/LL (CubeMX 호환)
    - arduino: Arduino 스케치
    - esp_idf: ESP-IDF (향후)
    """

    def __init__(self):
        self.pin_analyzer = PinAnalyzer()

    def generate(
        self,
        components: list[dict],
        nets: dict[str, list[str]],
        framework: str = "stm32_hal",
        board_name: str = "hwdesign-board",
    ) -> HALCodeResult:
        """
        HAL 초기화 코드 생성

        Args:
            components: 컴포넌트 목록
            nets: 넷 정보
            framework: "stm32_hal", "arduino"
            board_name: 보드 이름
        """
        # MCU 감지
        mcu_value = ""
        mcu_family = ""
        for comp in components:
            family = self.pin_analyzer.detect_mcu_family(comp.get("value", ""))
            if family:
                mcu_family = family
                mcu_value = comp.get("value", "")
                break

        # 주변장치 감지
        peripherals = self._detect_peripherals(nets)
        gpio_pins = self._detect_gpio_pins(nets)

        # 템플릿 렌더링
        if framework == "stm32_hal":
            code = STM32_HAL_TEMPLATE.render(
                board_name=board_name,
                mcu_value=mcu_value,
                peripherals=[{"type": p.periph_type, "instance": p.instance,
                              "speed": p.speed, "baudrate": p.baudrate} for p in peripherals],
                gpio_pins=[{"name": g.name, "port": g.port, "number": g.number,
                            "mode": g.mode, "pull": g.pull} for g in gpio_pins],
            )
        elif framework == "arduino":
            code = ARDUINO_TEMPLATE.render(
                board_name=board_name,
                mcu_value=mcu_value,
                has_i2c=any(p.periph_type == "I2C" for p in peripherals),
                has_spi=any(p.periph_type == "SPI" for p in peripherals),
                gpio_pins=[{"name": g.name, "arduino_pin": g.arduino_pin,
                            "mode": g.mode} for g in gpio_pins],
            )
        else:
            code = f"// Framework '{framework}' not yet supported"

        logger.info(f"HAL 코드 생성: {framework}, {len(peripherals)} 주변장치, {len(gpio_pins)} GPIO")
        return HALCodeResult(
            code=code,
            framework=framework,
            mcu_family=mcu_family,
            peripherals=peripherals,
            gpio_pins=gpio_pins,
        )

    def save(self, result: HALCodeResult, output_path: str) -> str:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(result.code, encoding="utf-8")
        result.output_path = output_path
        return output_path

    def _detect_peripherals(self, nets: dict) -> list[PeripheralInfo]:
        peripherals = []
        seen = set()
        for net_name in nets:
            func = self.pin_analyzer.infer_pin_function(net_name)
            if func in (PinFunction.I2C, PinFunction.SPI, PinFunction.UART, PinFunction.ADC):
                import re
                inst_match = re.search(r"(\d+)", net_name)
                instance = int(inst_match.group(1)) if inst_match else 1
                key = (func.value, instance)
                if key not in seen:
                    seen.add(key)
                    peripherals.append(PeripheralInfo(periph_type=func.value, instance=instance))
        return peripherals

    def _detect_gpio_pins(self, nets: dict) -> list[GPIOPin]:
        pins = []
        import re
        for net_name in nets:
            if self.pin_analyzer.infer_pin_function(net_name) == PinFunction.GPIO:
                port_match = re.search(r"P([A-Z])(\d+)", net_name)
                if port_match:
                    pins.append(GPIOPin(
                        name=net_name,
                        port=port_match.group(1),
                        number=int(port_match.group(2)),
                    ))
        return pins
